name: CI - E2E Upload

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build and start backend + db with Docker Compose
        run: |
          # find the docker-compose file in the repo (support different layouts)
          set -euo pipefail
          echo "repo root: $(pwd)"
          echo "listing top-level files:"; ls -la
          COMPOSE_FILE=$(find . -maxdepth 3 -type f -name 'docker-compose.yml' | head -n 1 || true)
          if [ -z "$COMPOSE_FILE" ]; then
            echo "ERROR: docker-compose.yml not found in repo (searched maxdepth 3)" >&2
            echo "You can inspect the repository tree with: find . -maxdepth 4 -print" >&2
            exit 1
          fi
          echo "Using compose file: $COMPOSE_FILE"
          COMPOSE_DIR=$(dirname "$COMPOSE_FILE")
          echo "Creating .env in $COMPOSE_DIR"
          cat > "$COMPOSE_DIR/.env" <<'EOF'
DATABASE_URL=postgresql://sihur:sihurpassword@db:5432/sihurdb?schema=public
JWT_SECRET=${{ secrets.JWT_SECRET }}
EOF
          docker compose -f "$COMPOSE_FILE" up -d --build db backend

      - name: Wait for backend
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:3001/api/health >/dev/null; then echo "backend up" && break; fi
            echo "waiting..."; sleep 3;
          done

      - name: Install root deps
        run: npm ci

      - name: Run E2E upload test
        env:
          CI: true
        run: npm run sihur:e2e-upload

      - name: Tear down
        if: always()
        run: |
          COMPOSE_FILE=$(find . -maxdepth 3 -type f -name 'docker-compose.yml' | head -n 1 || true)
          if [ -n "$COMPOSE_FILE" ]; then
            docker compose -f "$COMPOSE_FILE" down -v || true
          else
            echo "no compose file found during teardown"
          fi
